//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ProductStatus.
const (
	Archived  ProductStatus = "archived"
	Displayed ProductStatus = "displayed"
)

// Valid indicates whether the value is a known member of the ProductStatus enum.
func (e ProductStatus) Valid() bool {
	switch e {
	case Archived:
		return true
	case Displayed:
		return true
	default:
		return false
	}
}

// Product defines model for Product.
type Product struct {
	// Color Primary color scheme of the concrete unit
	Color *string `json:"color,omitempty"`

	// CreatedAt Timestamp when the item was added to the catalog
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Description Expanded marketing or technical details about the product
	Description *string `json:"description,omitempty"`

	// Id Unique internal identifier of the product
	Id openapi_types.UUID `json:"id"`

	// ImageUrls Ordered list of product demonstration images
	ImageUrls *[]ProductImage `json:"image_urls,omitempty"`

	// Price Price in the lowest currency unit (e.g., cents or kopecks) to avoid floating-point issues
	Price int `json:"price"`

	// Rating User evaluation metric
	Rating *int `json:"rating,omitempty"`

	// Size Dimensions blueprint schema mapping to your nested Go Size struct
	Size   *Size         `json:"size,omitempty"`
	Status ProductStatus `json:"status"`

	// StockQuantity Available stock units remaining in the warehouse inventory
	StockQuantity *int `json:"stock_quantity,omitempty"`

	// Title Name of the concrete product or paving stone
	Title string `json:"title"`

	// Type Category or material classification type
	Type string `json:"type"`

	// UpdatedAt Timestamp when the catalog entry was last modified
	UpdatedAt *time.Time `json:"updated_at,omitempty"`

	// Weight Unit or batch weight measurements
	Weight *int `json:"weight,omitempty"`
}

// ProductImage defines model for ProductImage.
type ProductImage struct {
	CreatedAt time.Time `json:"created_at"`

	// Id Unique image asset ID
	Id openapi_types.UUID `json:"id"`

	// Position Sorting priority index order for UI image galleries
	Position int `json:"position"`

	// ProductId Target product owner relationship ID
	ProductId int `json:"product_id"`

	// Url Public CDN or server web address string for the image file
	Url string `json:"url"`
}

// ProductStatus defines model for ProductStatus.
type ProductStatus string

// Size Dimensions blueprint schema mapping to your nested Go Size struct
type Size struct {
	Length    *int `json:"length,omitempty"`
	Thickness *int `json:"thickness,omitempty"`
	Width     *int `json:"width,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /v1/products)
	GetProducts(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetProducts operation middleware
func (siw *ServerInterfaceWrapper) GetProducts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProducts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/products", wrapper.GetProducts)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"lFffbxtHDv5XiL17SABZkt30UOgtl9zlDNw1Rp0+tYFBzVBaxrMzGw5Xilr4fz9wdiVL1iZx36RdLn98",
	"/Phx5s/KpaZNkaLmavFnlV1NDZafN5J859R+tpJaEmUqL1wKSeyHp+yEW+UUq0V1I9yg7KC8huKIIK1A",
	"awKXohNSgi6yVpOKvmDTBqoW1TvByErwTnBXTarYhYBLe6PS0aTSXWtWWYXjunqYVE4Ilfwd6nkGH7ih",
	"rNi0sK0plsCs1MAWM6D35EFTnw4qhrSuJtUqSWOuKo9KF8oNVSNBT8I8jfqvLy1Gc96g3JNyXEMSUHJ1",
	"ZIcBPClyyIDL1GkJ3w7IHuPwH17XF74TXHJg3T0i1uLGXGZNkSbQkqzIKaySwBbD/RZ3GTB68MIbsn/T",
	"56DI/ryOXyN/7gg4KknEAOwpKq+YZN/Fkbwv55dHIHYd+zH8uME13XUS8nnY9+JJyEPgrBZoCAKemhSz",
	"CpodFA+5mlTW0OLl70KralH9bfZI4NnA3tlA3Wv7yOIPCaEYyR4mVSvsaJTBzgAoxYa0pazgOhGKbleY",
	"Cy9oup5OwFk06/J9asnd55dGLNwk9rAKCY0DF23iqMA5dyXvA2I//Difzw8pGdprEktKyncjfckkQBsM",
	"XQ9FQyrsjl3++NWOH7nP/Ad9D7dbszFbRe2ei/Jtb1w+S+7+7nOHUVl355W83iCXLKFYFkgzCDXI0Tg+",
	"IL9FoTp12VqxoahJdieUuzL8vl+wsoaRJv+MI7K0J12Sk3k7mdD3wcOHtI1w01vcDhZnbO8fPI37BpXW",
	"SXYWo0ElYQzgAubMK3Z9a8uXxzH7ZO7y10J1rf8rajjoHlBU2RVZDJgVmuRtzv2z9XBLvK51VEIKhktU",
	"V0NvBQ1h7oSasmKOinv1DNraWNDnjoV8tfitKurSD+++v8M3B85+PDhJy0/k1NI9kYPzdXayUZ4HwLf0",
	"06IA5kwK12+rZ6hjmzKPr5bbJGWftMJJbCtw9PQFkklmWQG/Xg/x1hgCCZ9KzeXYWAxUvxsr4QPKmvRx",
	"GraRBIRCYWeuue0rOlX/8xCdhBFx7ZaBHbx5+7MxJJNsSGBLS9vMQjlDD0gpq2zuUteKw+lE1KptXsxm",
	"zsfpkjTFqUvNrF8PsxT8haZtvFgL7qaf2pMN3wmfoz9OsANCR83pyzo5gHyDa7cHBaXYNebac24D7sqU",
	"obiaN+TNw2NpxxZnJLkd5PsU1LfcUMzWHFiGjlqxndPrMzTYtgaoJtilTiBSVvLwLoH5Mrj7XX46DYHi",
	"WuuS+D6xq/F9pTW7+0g5nxj/Y9R2y/6J08sxpw9ngNojjqtUzqZdYwdM42nNGd63FF/fXBtbN+wpA8e+",
	"JlPSOm2tcFsiS3T3FD3UGH0oAzJshuqfxp+9n2pSbUhyj+vldD6dW+KppYgtV4vqh+nVdG5wodal5Nnm",
	"cjZQpfxf04gi/kLaScyAIRwfoTJsWeth333uSHbQomCTIXDDCtzvp+FPtqaSHj1a7sDTCrtgb+FqPrFK",
	"BWo76DpHOU8gd64+Clezq6HGjTXeqAlD23dwAQfiTeE6Duqiqbfu3ZXQw+F5T17oINepC34w9A1HkBTI",
	"TqDmu6jGtbdDPunNHilDULAhJcnV4rengP2bg5I8Jr7cDQlP4bVFyOAwQos5w++HOfq9Kvmy9xQPS66c",
	"FC0XNr8F5GGcJlXEph+vMqWT4drTt6/A+mQcvzfET1Xlo8lKblPM/VRdzef9zSkqxUITbNswrP3Zp9yL",
	"/2MWzzh29bNxCl7uSreMuK/mr74f8dxDTHqxSl305t5e90I91qn/pv52s6GQWtvue1F/sZ+4/v/LQTp7",
	"7V7MZsE+rFPWxU/zn+aVgaW47kPcczTCYOeZoqNytcmKq9Vj0153WlvLDmpgD+yqMhyi7JPySPiP/sl+",
	"pdiM5COXD5PzcW2Fsjlbg2nmQMMp/A8jrkuRp3chm+ycADut01m8fiRajBSMh8+o7dDbb2ZmvsuU5sNB",
	"NnC5kpRkzl+XKPCCvrRkjJzYOYLF7pEcXWooA6mbvnxejuXCVjJ8Yvxo8iZFxbJcHrv0CznicnB2/Vsw",
	"Xe/vrpRZKMNKUnNcTvXw8eH/AQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
