name: CI beton

on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: beton_test_user
          POSTGRES_PASSWORD: ${{ secrets.BETON_TEST_PASSWORD }}
          POSTGRES_DB: beton_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.26
          cache: true

      - name: Install Goose Migration Tool
        run: |
          curl -fsSL https://raw.githubusercontent.com/pressly/goose/master/sh/goose.sh | sh
          sudo mv goose /usr/local/bin/

      - name: Run Database Migrations
        env:
          DB_TEST_CONN_STR: "postgres://beton_test_user:${{ secrets.BETON_TEST_PASSWORD }}@localhost:5432/beton_test?sslmode=disable"
        run: goose -dir ./internal/migrations postgres "$DB_TEST_CONN_STR" up

      - name: Run Go Tests
        env:
          SECRET: "super-secret-fake-test-key-123"
          CONFIG_PATH: "config.ci.yaml"
        run: go test -v ./...
